const MODERN_ICONS_BASE = '/src/assets/icons/fileicons/theme-modern-icons/fileicons/images'

export const MODERN_FILE_ICONS = {
  '.js': 'javascript',
  '.mjs': 'javascript',
  '.cjs': 'javascript',
  '.jsx': 'react',
  '.ts': 'typescript',
  '.tsx': 'react',
  '.py': 'python',
  '.pyw': 'python',
  '.rb': 'ruby',
  '.erb': 'html',
  '.go': 'go2',
  '.rs': 'rust',
  '.c': 'file',
  '.h': 'file',
  '.cpp': 'file',
  '.hpp': 'file',
  '.cs': 'file',
  '.java': 'java',
  '.kt': 'kotlin',
  '.kts': 'kotlin',
  '.swift': 'swift',
  '.scala': 'scala',
  '.hs': 'haskell',
  '.lhs': 'haskell',
  '.ml': 'ocaml',
  '.mli': 'ocaml',
  '.fs': 'fsharp',
  '.fsx': 'fsharp',
  '.lua': 'lua',
  '.r': 'r',
  '.dart': 'file',
  '.html': 'html',
  '.htm': 'html',
  '.css': 'css',
  '.scss': 'sass',
  '.sass': 'sass',
  '.less': 'less',
  '.styl': 'stylus',
  '.svg': 'svg',
  '.vue': 'vue',
  '.svelte': 'svelte',
  '.json': 'json',
  '.jsonc': 'json',
  '.xml': 'xml',
  '.yaml': 'settings',
  '.yml': 'settings',
  '.toml': 'settings',
  '.ini': 'settings',
  '.env': 'settings',
  '.md': 'markdown',
  '.mdx': 'markdown',
  '.txt': 'file',
  '.sql': 'file',
  '.graphql': 'graphql',
  '.gql': 'graphql',
  '.sh': 'shell',
  '.bash': 'shell',
  '.zsh': 'shell',
  '.fish': 'shell',
  '.ps1': 'powershell',
  '.psm1': 'powershell',
  '.bat': 'windows',
  '.cmd': 'windows',
  '.php': 'php',
  '.twig': 'twig',
  '.ejs': 'file',
  '.hbs': 'file',
  '.mustache': 'file',
  '.haml': 'haml',
  '.jade': 'file',
  '.pug': 'file',
  '.ttf': 'file',
  '.otf': 'file',
  '.woff': 'file',
  '.woff2': 'file',
  '.eot': 'file',
  '.pdf': 'pdf',
  '.zip': 'file',
  '.gz': 'file',
  '.tar': 'file',
  '.7z': 'file',
  '.rar': 'file',
  '.jpg': 'image',
  '.jpeg': 'image',
  '.png': 'image',
  '.gif': 'image',
  '.webp': 'image',
  '.ico': 'image',
  '.bmp': 'image',
  '.tiff': 'image',
  '.mp3': 'file',
  '.mp4': 'video',
  '.avi': 'video',
  '.mov': 'video',
  '.wmv': 'video',
  '.flv': 'video',
  '.webm': 'video',
  '.mkv': 'video',
  '.wasm': 'wasm',
  '.wat': 'wat',
}

export const MODERN_FILE_NAMES = {
  'Dockerfile': 'file',
  'docker-compose.yml': 'settings',
  'docker-compose.yaml': 'settings',
  '.gitignore': 'gitignore',
  '.gitconfig': 'git',
  '.eslintrc': 'settings',
  '.eslintrc.js': 'settings',
  '.eslintrc.json': 'settings',
  '.eslintrc.yml': 'settings',
  '.prettierrc': 'settings',
  '.prettierrc.json': 'settings',
  'tsconfig.json': 'tsconfig',
  'package.json': 'npm',
  'package-lock.json': 'npm',
  'yarn.lock': 'yarn',
  'pnpm-lock.yaml': 'yarn',
  'vite.config.js': 'settings',
  'vite.config.ts': 'settings',
  'webpack.config.js': 'settings',
  'webpack.config.ts': 'settings',
  'rollup.config.js': 'settings',
  'babel.config.js': 'settings',
  'babel.config.json': 'settings',
  '.babelrc': 'settings',
  'Makefile': 'file',
  'Cargo.toml': 'rust',
  'go.mod': 'go2',
  'go.sum': 'go2',
  'pom.xml': 'file',
  'build.gradle': 'gradle',
  'Gemfile': 'ruby',
  'README.md': 'markdown',
  'README.txt': 'markdown',
  'CHANGELOG.md': 'file',
  'LICENSE': 'license',
  'LICENSE.md': 'license',
  'TODO.md': 'file',
  'firebase.json': 'settings',
  '.firebaserc': 'settings',
  'vercel.json': 'settings',
  'netlify.toml': 'settings',
  'platformio.ini': 'settings',
  '.editorconfig': 'settings',
}

export const MODERN_FOLDER_ICONS = {
  'node_modules': 'npm',
  '.git': 'git',
  '.github': 'github',
  '.gitlab': 'gitlab',
  'src': 'folder',
  'lib': 'folder',
  'dist': 'folder',
  'build': 'folder',
  'public': 'folder',
  'assets': 'image',
  'images': 'image',
  'icons': 'image',
  'fonts': 'file',
  'styles': 'css',
  'css': 'css',
  'scss': 'sass',
  'components': 'react',
  'pages': 'html',
  'utils': 'settings',
  'helpers': 'settings',
  'hooks': 'react',
  'services': 'settings',
  'store': 'settings',
  'redux': 'settings',
  'api': 'settings',
  'tests': 'file',
  'test': 'file',
  '__tests__': 'file',
  'spec': 'file',
  'docs': 'markdown',
  'doc': 'markdown',
  '.vscode': 'settings',
  '.idea': 'settings',
  'config': 'settings',
  'scripts': 'shell',
  'bin': 'shell',
  'tools': 'shell',
  'types': 'typescript',
}

export function getModernIcon(filename) {
  const lower = filename.toLowerCase()

  if (MODERN_FILE_NAMES[filename]) return MODERN_FILE_NAMES[filename]
  if (MODERN_FILE_NAMES[lower]) return MODERN_FILE_NAMES[lower]

  const ext = '.' + lower.split('.').pop()
  if (MODERN_FILE_ICONS[ext]) return MODERN_FILE_ICONS[ext]

  return 'file'
}

export function getModernFolderIcon(foldername) {
  const lower = foldername.toLowerCase()
  return MODERN_FOLDER_ICONS[lower] || 'folder'
}

export function getModernIconPath(iconName) {
  return `${MODERN_ICONS_BASE}/${iconName}.svg`
}
